//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SampleServiceParameters.proto
namespace ProtoBufRemote.Test
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MultiplyInput")]
  public partial class MultiplyInput : global::ProtoBuf.IExtensible
  {
    public MultiplyInput() {}
    

    private string _prefix = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"prefix", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Prefix
    {
      get { return _prefix; }
      set { _prefix = value; }
    }
    private int _firstNumber;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"first_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int FirstNumber
    {
      get { return _firstNumber; }
      set { _firstNumber = value; }
    }
    private int _secondNumber;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"second_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SecondNumber
    {
      get { return _secondNumber; }
      set { _secondNumber = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MultiplyOutput")]
  public partial class MultiplyOutput : global::ProtoBuf.IExtensible
  {
    public MultiplyOutput() {}
    
    private string _resultString;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"result_string", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ResultString
    {
      get { return _resultString; }
      set { _resultString = value; }
    }
    private int _resultNumber;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"result_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ResultNumber
    {
      get { return _resultNumber; }
      set { _resultNumber = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
