//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RpcMessage.proto
namespace ProtoBufRemote
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpcMessage")]
  public partial class RpcMessage : global::ProtoBuf.IExtensible
  {
    public RpcMessage() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Id
    {
      get { return _id; }
      set { _id = value; }
    }

    private ProtoBufRemote.RpcMessage.Call _callMessage = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"call_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBufRemote.RpcMessage.Call CallMessage
    {
      get { return _callMessage; }
      set { _callMessage = value; }
    }

    private ProtoBufRemote.RpcMessage.Result _resultMessage = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBufRemote.RpcMessage.Result ResultMessage
    {
      get { return _resultMessage; }
      set { _resultMessage = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Call")]
  public partial class Call : global::ProtoBuf.IExtensible
  {
    public Call() {}
    
    private string _service;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"service", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Service
    {
      get { return _service; }
      set { _service = value; }
    }
    private string _method;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"method", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Method
    {
      get { return _method; }
      set { _method = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBufRemote.RpcMessage.Parameter> _parameters = new global::System.Collections.Generic.List<ProtoBufRemote.RpcMessage.Parameter>();
    [global::ProtoBuf.ProtoMember(3, Name=@"parameters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBufRemote.RpcMessage.Parameter> Parameters
    {
      get { return _parameters; }
    }
  
    private bool _expectsResult;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"expects_result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool ExpectsResult
    {
      get { return _expectsResult; }
      set { _expectsResult = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Result")]
  public partial class Result : global::ProtoBuf.IExtensible
  {
    public Result() {}
    

    private bool _isFailed = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"is_failed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsFailed
    {
      get { return _isFailed; }
      set { _isFailed = value; }
    }

    private string _errorMessage = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"error_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ErrorMessage
    {
      get { return _errorMessage; }
      set { _errorMessage = value; }
    }

    private ProtoBufRemote.RpcMessage.Parameter _callResult = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"call_result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBufRemote.RpcMessage.Parameter CallResult
    {
      get { return _callResult; }
      set { _callResult = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Parameter")]
  public partial class Parameter : global::ProtoBuf.IExtensible
  {
    public Parameter() {}
    

    private byte[] _protoParam = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"proto_param", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] ProtoParam
    {
      get { return _protoParam; }
      set { _protoParam = value; }
    }

    private string _stringParam = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"string_param", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string StringParam
    {
      get { return _stringParam; }
      set { _stringParam = value; }
    }

    private int _intParam = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"int_param", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int IntParam
    {
      get { return _intParam; }
      set { _intParam = value; }
    }

    private uint _uintParam = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"uint_param", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UintParam
    {
      get { return _uintParam; }
      set { _uintParam = value; }
    }

    private long _int64Param = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"int64_param", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long Int64Param
    {
      get { return _int64Param; }
      set { _int64Param = value; }
    }

    private ulong _uint64Param = default(ulong);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"uint64_param", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong Uint64Param
    {
      get { return _uint64Param; }
      set { _uint64Param = value; }
    }

    private bool _boolParam = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"bool_param", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool BoolParam
    {
      get { return _boolParam; }
      set { _boolParam = value; }
    }

    private float _floatParam = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"float_param", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float FloatParam
    {
      get { return _floatParam; }
      set { _floatParam = value; }
    }

    private double _doubleParam = default(double);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"double_param", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double DoubleParam
    {
      get { return _doubleParam; }
      set { _doubleParam = value; }
    }

    private bool _isNull = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"is_null", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsNull
    {
      get { return _isNull; }
      set { _isNull = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
